<?php
/**
 * @file
 * Random Frontpage primary module file.
 * get all the node types and Names defined in the system
 */
function random_frontpage_gettypes() {
  $nodetypes = array();

  $type_query = db_query('SELECT type, name FROM {node_type}');

  while ($row = $type_query->fetchAssoc()) {
    $nodetypes[$row['type']] = $row['name'];
  } 	
  return $nodetypes;
} 


/**
 * Implements hook_admin().
 * admin form
 */
function random_frontpage_admin() {
  $form = array();

  $form['nodetypes'] = array(
    '#type' => 'select',
    '#title' => t('Random page node type'),
    '#options' => random_frontpage_gettypes(),
    '#default_value' => variable_get('nodetypes', 'Node Types'),
    '#description' => "Please select the node type you wish to display at the URL '/frontpage'",
    '#required' => TRUE,
  );

  return system_settings_form($form);
}


/**
 * Implements hook_menu().
 */
function random_frontpage_menu() {
  $items = array();

  $items['frontpage'] = array(
    'page callback' => 'random_frontpage_view',
    'access arguments' => array('access content'),
  );
  $items['admin/config/system/random_frontpage'] = array(
    'title' => 'Random Frontpage',
    'description' => 'Random Frontpage settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('random_frontpage_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}


/**
 * Implements hook_validate().
 * Database updates
 */
function random_frontpage_admin_validate($form, &$form_state) {

  $nodetypes = $form_state['values']['nodetypes'];
  $result = db_truncate('random_frontpage')->execute();
  $query = db_insert('random_frontpage')->fields(array('nodetype' => $nodetypes))->execute();
}


/**
 * displays a random node of the selected content type.
 */
function random_frontpage_view() {
  $nodetype = db_query('SELECT nodetype FROM {random_frontpage} WHERE 1')->fetchField();

/** check to see if the user has configured a node type choice in admin 
 * In case we don't have any nodes at all in the system when we install the module 
 * we output a placeholder page prompting the user to configure a choice  
 */
  $textoutput = "Please set a node type to randomize at <a href='/admin/config/system/random_frontpage'>/admin/config/system/random_frontpage</a>.";

  if ($nodetype) {
    $nodeids = array();
    $nid_query = db_query('SELECT nid FROM {node} WHERE type = :' . $nodetype, array(':' . $nodetype => $nodetype));

    while ($row = $nid_query->fetchAssoc()) { 
      $nodeids[] = $row['nid'];
    } 	

    if (count($nodeids) != 1) {
/** pick a random NID */
      $key = array_rand($nodeids, 1);
      $nid = $nodeids[$key];
    }

    if (count($nodeids) == 1) {
      $nid = $nodeids[0];
    }

    $node = node_load($nid);

    if (isset($node)) {
      $node_view = node_view($node);
      $rendered_node = drupal_render($node_view);
    }

    if (isset($rendered_node)) {
      return $rendered_node;
    }

  } else return $textoutput;
}
